"""Initial migration

Revision ID: 0c1ca1eaed32
Revises: 
Create Date: 2025-01-21 01:52:23.547292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1ca1eaed32'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create the `profiles` table with updated columns and constraints
    op.alter_column('profiles', 'height', new_column_name='height_cm')



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'height_cm', new_column_name='height')
