"""Fix MeasurementSystem enum handling

Revision ID: 2038967e57ce
Revises: 209fadddda10
Create Date: 2025-01-21 02:19:12.484512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2038967e57ce'
down_revision: Union[str, None] = '209fadddda10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
