"""Switch to SQLAlchemy Enum for Profile

Revision ID: 209fadddda10
Revises: 740e180e418c
Create Date: 2025-01-21 02:17:24.974047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '209fadddda10'
down_revision: Union[str, None] = '740e180e418c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
