"""Update weight types

Revision ID: 65170c04b069
Revises: 8a71f8a05e62
Create Date: 2025-01-22 00:38:37.354687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65170c04b069'
down_revision: Union[str, None] = '8a71f8a05e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Update FREE_WEIGHTS to OTHER
    op.execute("""
        UPDATE exercises 
        SET weight_type = 'OTHER' 
        WHERE weight_type = 'FREE_WEIGHTS'
    """)
    
    # Update MACHINES to MACHINE
    op.execute("""
        UPDATE exercises 
        SET weight_type = 'MACHINE' 
        WHERE weight_type = 'MACHINES'
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
