"""Update workout exercise relationships

Revision ID: 9bf0c24c3955
Revises: cf3b1bf79770
Create Date: 2025-01-22 01:07:51.350811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bf0c24c3955'
down_revision: Union[str, None] = 'cf3b1bf79770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
