# Dockerfile
FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the app code
COPY . .

# Run the data population script on container startup
CMD ["sh", "-c", "python app/init/populate_exercises.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"]
